repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: check-yaml
  - id: check-json
  - id: check-toml
  - id: check-added-large-files
  - id: check-ast
  - id: check-merge-conflict
- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
    - id: black
- repo: local
  hooks:
    - id: pytest-check
      name: pytest-check
      entry: pytest
      language: system
      always_run: true
      stages: [push]